/* eslint-disable */

const TournamentCreateDtoInType = shape({
    name: uu5String(255).isRequired(),
    description: uu5String(1000),
    startDate: uu5String(255).isRequired(),
    endDate: uu5String(255).isRequired(),
    status: uu5String(255).isRequired(),
    teamSize: uu5String(255).isRequired(),
    teams: array(),
    owner: uu5String(255).isRequired()
        

})

const TournamentUpdateDtoInType = shape({
    name: uu5String(255),
    description: uu5String(1000),
    startDate: date(),
    endDate: date(),
    status: oneOf(["ongoing", "finished", "cancelled", "upcoming"]),
    teamSize: integer(),
    teams:
        shape({
            id: uu5String(255).isRequired()

        })

})

const TournamentGetDtoInType = shape({
    id: uu5String(255).isRequired()
})

const TournamentDeleteDtoInType = shape({
    id: uu5String(255).isRequired()
})



// const tournamentSchema = {
//   _id: ObjectId,                    // auto-generated by MongoDB
//   name: String,                     // unique
//   description: String,
//   startDate: Date,                  // tournament start
//   endDate: Date,                    // tournament end
//   status: "ongoing" | "finished" | "cancelled" | "upcoming" | "registration",
//   teamSize: Number,                 // default 4
//   teams: [                          // embedded or referenced teams
//     {
//       _id: ObjectId,                // reference to Team
//       name: String
//     }
//   ]
// }
